### PR TITLE
Implement intersection

### LINKED ISSUE #18: Implement intersection
Hey, thanks for this super handy gem! We got halfway through implementing this ourselves today for time ranges, but switched over to this when we found it; and it passed all our specs once we filtered out empty ranges.

For our next piece of work, we need to get the intersection of several multi-ranges. I'd imagine this can be done by implementing intersection between two multi-ranges, e.g.:

```ruby
a = MultiRange.new([1...3, 5...10])
b = MultiRange.new([2...6, 8...9])
a.intersection(b).ranges == [2...3, 5...6, 8...9]
```

so then we could run something like:

```ruby
multi_ranges.reduce(&:intersection)
```

We'd be looking at implementing this tomorrow, and will submit a PR.

### PR DESCRIPTION
**Pull request by chrisnankervis**
Resolves #18.

In order to implement intersection, we could have gone with nested iterated loops over the list of ranges but the time that'd take very quickly becomes unmanageable. Instead, we use an [interval tree](https://en.wikipedia.org/wiki/Interval_tree) to avoid the naive iteration cost. We found a gem that implements interval trees well, so we decided to use it.

However, the performance of the `augmented_interval_tree` gem as implemented is not usable for large ranges - we have improved it and this branch uses our fork, published as `fast_interval_tree`, found here: https://github.com/greensync/interval-tree

The interval tree converts interval endings to exclusive, so we need to restore the original. We haven't implemented that in the gem yet, so we've had to do that here.

### CODE REVIEW

**Comment by chrisnankervis** [comment]
We just noticed that the build is failing on older Rubies; we'll get to this this evening.

**Comment by ZimbiX** [comment]
Ok, all done! =)

**Comment by khiav223577** [comment]
Very nice! :rocket: 

I notice that this PR [drops the support for Ruby 1.8.7](https://github.com/khiav223577/multi_range/pull/19/commits/74a2f45c0316d5418420d843bd2c8ec7a2cdd361). I'll create another PR to drop the support, update documentation, and setup `travis` to test Ruby 1.9.3. It would be better to be separated to different PRs since the [CHANGELOG](https://github.com/khiav223577/multi_range/blob/master/CHANGELOG.md) is auto-generated by PRs, and it'll make your PR simpler :).

Though some of my old [projects](https://gamejolt.com/games/echo/295185) are still running in Ruby 1.8.7 :disappointed:, we can have a major release and keep it using 1.x.x.

**Comment by khiav223577** [comment]
Hi @chrisnankervis, @ZimbiX, 
I've dropped the support for Ruby < 2 in https://github.com/khiav223577/multi_range/pull/20. 

Could you rebase or merge the latest master branch to recalculate the files diffs.

**Comment by chrisnankervis** [comment]
Can do @khiav223577, I'll try and take a look at this today 👍

**Comment by chrisnankervis** [comment]
@khiav223577 sorry for the delay, this branch should be up to date now.

**Comment by khiav223577** [comment]
Thanks. It looks nice to me.

**Comment by khiav223577** [comment]
I just release multi_range 2.0 :). For more details, see the [CHANGELOG](https://github.com/khiav223577/multi_range/blob/master/CHANGELOG.md).

**Comment by chrisnankervis** [comment]
Thanks for that @khiav223577 🥳

**Pull request merged**
